### ISSUE TITLE
when can cefpython support android

### ISSUE THREAD

**Issue by nkiiiiid** [kivy-garden/garden.cefpython#8]
my code use garden.cefpython to display a flash，then i package the code into app run on Android, but something got wrong with it. i use adb logcat get log show below:

```
W/ActivityManager(  960): No content provider found for permission revoke: file:///storage/sdcard1/DecryptVideo-0.1-debug.apk
W/ActivityManager(  960): No content provider found for permission revoke: file:///storage/sdcard1/DecryptVideo-0.1-debug.apk
I/python  (11343):    File "/home/crossx/kivy/decryptVideo/.buildozer/android/app/main.py", line 19, in <module>
I/python  (11343):    File "/home/crossx/kivy/decryptVideo/.buildozer/android/platform/build/dists/decrypt/private/lib/python2.7/site-packages/kivy/garden/__init__.py", line 100, in load_module
I/python  (11343):    File "/home/crossx/kivy/decryptVideo/.buildozer/android/platform/build/dists/decrypt/private/lib/python2.7/site-packages/kivy/garden/__init__.py", line 104, in _load_module
I/python  (11343):    File "/home/crossx/kivy/decryptVideo/.buildozer/android/app/libs/garden/garden.cefpython/__init__.py", line 33, in <module>
```

cefpython couldn't runs on android, how to solve it, or how to show a flash from website with kivy on android?

**Comment by jegger** [comment]
I am not aware that garden.cefpython runs on android. I do not think that this is possible at the moment. But there seems to be a webview https://github.com/kivy/kivy/wiki/Android-native-embedded-browser

**Comment by nkiiiiid** [comment]
@jegger thanks！i will try to use webview, by the way, is there a plan to porting cefpython to Android?

**Comment by jegger** [comment]
At this time CEF does not seem to run an android at all. https://bitbucket.org/chromiumembedded/cef/issues/1991/add-android-support
